version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fraudshield_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fraudshield
      MYSQL_USER: frauduser
      MYSQL_PASSWORD: fraudpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fraudshield_backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=frauduser
      - DB_PASSWORD=fraudpassword
      - DB_NAME=fraudshield
      - SECRET_KEY=supersecretkey_for_fraudshield_ai_enterprise
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ml_engine/models:/app/ml_engine/models:ro # Mount models as read-only
      - ./reports:/app/reports
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraudshield_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
